version: "3"

services:
  anro-mongo:
    image: mongo:4.4-bionic
    ports: 
      - 5000:27017
    volumes: 
      - anro-mongo-data:/data/db
    environment: 
      MONGO_INITDB_ROOT_USERNAME: anro-admin
      MONGO_INITDB_ROOT_PASSWORD: anro-pass
    logging:
      driver: "none" # Mongo pollutes the logs a fuck ton, remove this if need to see em
    
  anro-service:
    build: ./anro-service
    volumes:
      - ./anro-service:/home/anro-service # TODO make a dockerfile for this too so we can pull the same trick to ignore node_modules used in anro-webapp
      - /home/anro-service/node_modules
    expose: 
      - 5001
    ports: 
      - 5001:5001
    depends_on: 
      - anro-mongo

  anro-webapp:
    build: ./anro-webapp
    volumes: 
      - ./anro-webapp:/home/anro-webapp
      - /home/anro-webapp/node_modules # excludes node_modules
    expose: 
      - 5002
    ports: 
      - 80:5002
    depends_on: 
      - anro-service

volumes: 
  anro-mongo-data: